url: http://responsive.ly
name: Responsive.ly
description: TBD
paginate: 10
pygments: true
permalink: /:year/:month/:title/
markdown: rdiscount
author: Doug Gapinski and Erik Runyon
email:
feed: /atom.xml
authors:
  doug: Doug Gapinski (<a href="http://www.twitter.com/thedougco/">@thedougco</a>)
  erik: Erik Runyon (<a href="http://www.twitter.com/erunyon/">@erunyon</a>)
erik: "Erik Runyon"
exclude:
  - README.md